name: disjoint_set
description: A highly efficient implementation of the Disjoint Set (Union-Find) data structure with union by rank and path compression optimizations.
version: 1.0.0
homepage: https://github.com/kxtxr/disjoint_set
repository: https://github.com/kxtxr/disjoint_set
issue_tracker: https://github.com/kxtxr/disjoint_set/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
