name: Dart Package CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test

  coverage:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Install coverage tools
        run: dart pub global activate coverage

      - name: Collect coverage
        run: |
          dart pub global run coverage:collect_coverage \
            --port=8181 \
            --out=coverage.json \
            --wait-paused \
            --resume-isolates \
            &
          dart --pause-isolates-on-exit --enable-vm-service=8181 \
            test/disjoint_set_test.dart
          dart pub global run coverage:format_coverage \
            --lcov \
            --in=coverage.json \
            --out=lcov.info \
            --packages=.packages \
            --report-on=lib

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: lcov.info
          fail_ci_if_error: false

